services:
  tg_api:
    build: .
    container_name: tg_telethon_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Храним сессии снаружи контейнера, чтобы не терять авторизацию
      - ./sessions:/app/sessions

