services:
  tg_api:
    build: .
    container_name: tg_telethon_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Храним сессии снаружи контейнера, чтобы не терять авторизацию
      - ./sessions:/app/sessions
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: tg_postgres
    restart: unless-stopped
    profiles:
      - all
      - vpn
    environment:
      POSTGRES_DB: tg_client
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8npass}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tg_user -d tg_client"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: tg_adminer
    restart: unless-stopped
    profiles:
      - all
      - vpn
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    profiles:
      - all
      - vpn
    ports:
      - "5678:5678"
    environment:
      N8N_PORT: 5678
      N8N_HOST: 0.0.0.0
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER:-user}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD:-user}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL:-http://127.0.0.1:5678}
      WEBHOOK_URL: ${WEBHOOK_URL:-http://127.0.0.1:5678}
      N8N_SECURE_COOKIE: "false"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./FrontEnd
    container_name: tg_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - tg_api
    networks:
      - app-network

  proxy:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: tg_proxy
    restart: unless-stopped
    profiles:
      - vpn
    command: ["run", "-c", "/etc/sing-box/config.json"]
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config.json:/etc/sing-box/config.json:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
